apiVersion: v1
kind: Pod
metadata:
  name: fssfendpod
  labels:
    app: greet
    tier: frontend
spec:
  containers:
    - name: fssfendps
      image: excontainer:v1
      ports:
        - containerPort: 8081